### ISSUE TITLE
Bot playlist controls can be improved...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#56] opened 2020-06-08 04:05 UTC
**Is your feature request related to a problem? Please describe.**
Anyone can stop the music instead of the voting system like other bots have. Ex. I'm always frustrated when someone skips the song without asking anyone in the voice channel...

**Describe the solution you'd like**
I would like a simillar voting system like other bots have (add react to vote feature if you want instead of commands)

**Comment by eritislami** [comment] 2020-06-08 13:52
Closing as duplicate of #55

**Closed by eritislami** 2020-06-08 13:52 UTC
Labels: enhancement
