### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by dmason94** [eritislami/evobot#107] opened 2020-06-28 10:16 UTC
Do you have any ideas around adding permissions to the code? For example, only certain roles in the server can perform any of the commands on the code rather than just everyone? I have the code for the permissions but have no idea where to input it in the code

**Comment by eritislami** [comment] 2020-06-28 14:42
Duplicate of #100 
Please follow the discussion there.

**Closed by eritislami** 2020-06-28 14:42 UTC
Labels: enhancement
