### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ashhwxn** [eritislami/evobot#788] opened 2021-07-10 10:11 UTC
im currently facing an error which says error code 429 pls help

**Comment by andreasflys** [comment] 2021-07-10 14:42
Error Code 429 could mean a lot of things:

Main thing is most likely the connection with the Bot to the YouTube Api.

**Comment by wolf-yuan-6115** [comment] 2021-07-10 14:46
https://github.com/eritislami/evobot/issues/623

**Comment by SrIzan10** [comment] 2021-07-28 13:54
Duplicate of #623

**Closed** 2021-08-06 13:43 UTC
Labels: bug: unconfirmed
