### ISSUE TITLE
EvoBot is not able to play some YT clips (TypeError)🐛 

### ISSUE THREAD

**Issue by MeetSova** [eritislami/evobot#1493] opened 2023-09-24 18:07 UTC
**Describe the bug**
music bot is not able to play some YT clips it responds with an error:
![obraz](https://github.com/eritislami/evobot/assets/43954480/ac68327f-6fa0-4b40-8ded-d9675d431b89)

This behaviour seems to be more frequent for clips that have more than 1 million views. Sometimes it evens report an error but plays the clip anyway

**How To Reproduce**
1.Start the bot
2.type /play and paste the url or keyword of clip from  YT
 
**Expected behavior**
Clips are played without any issues and error returned

**Environment (add if possible)**
* Node.js version: v18.16.0

**Comment by tuttizpro218** [comment] 2023-09-24 18:12
play-dl issue, as the error said, and [here](https://github.com/eritislami/evobot/issues/1489) got explained. :)

**Comment by tuttizpro218** [comment] 2023-09-24 18:21
Edit your package.json file
Go to line 37 `"play-dl": "^1.9.6",` change it to `"play-dl": "^1.9.7",`

And run `npm install`

**Comment by eritislami** [comment] 2023-09-24 21:08
Duplicate of https://github.com/eritislami/evobot/issues/1493

**Closed by eritislami** 2023-09-24 21:08 UTC
