### ISSUE TITLE
Bot stops working if too many people send messages at the same time

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#61] opened 2020-06-10 08:16 UTC
**Describe the bug**
Bot stops working if too many people send messages at the same time.

**How To Reproduce**
1.spam play command in chat 2-4 times.
2.after about 2-4 messages when you try to stop the song, it gives an error.
 
**Expected behavior**
I think the bot should wait for earlier commands to get executed completely, So after a command completely is executed then only it will respond to another message from the user.

**Environment (add if possible)**
* Node.js version: 12.^

**Additional information & screenshots**
Error
```
TypeError: Cannot read property 'end' of null
    at ReactionCollector.<anonymous> (D:\Other\Bot Coding\Bots\evobot\include\play.js:119:41)
    at ReactionCollector.emit (events.js:327:22)
    at ReactionCollector.handleCollect (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\structures\interfaces\Collector.js:100:12)
    at Client.emit (events.js:327:22)
    at MessageReactionAdd.handle (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\client\actions\MessageReactionAdd.js:44:17)
    at Object.module.exports [as MESSAGE_REACTION_ADD] (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_REACTION_ADD.js:4:37)
    at WebSocketManager.handlePacket (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (D:\Other\Bot Coding\Bots\evobot\node_modules\ws\lib\event-target.js:125:16)
(node:13780) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\Other\Bot Coding\Bots\evobot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eritislami** [comment] 2020-06-12 07:00
I can't reproduce your issue, i tried spamming play command much more than 10 times and it never crashed

**Comment by ParasDeshpande** [comment] 2020-06-12 09:27
Can poor network connectivity affect the bot?

**Comment by eritislami** [comment] 2020-06-14 09:13
Going to close this until we have something that can be reproduced.

**Closed by eritislami** 2020-06-14 09:13 UTC
Labels: bug: unconfirmed
