### ISSUE TITLE
Bug: Error 410 while requesting specific YouTube song

### ISSUE THREAD

**Issue by KAAquilla** [eritislami/evobot#942] opened 2021-09-24 20:41 UTC
**Describe the bug**
Whenever I want to play a specific song, the bot returns error 410. I also tried with multiple hosts and local. Most other songs work. Haven't tested for too long so there are probably more songs than just this one. Additional info and screenshot down below.

**How To Reproduce**
1. !play https://www.youtube.com/watch?v=TIdAVlXIjLk
2. Bot returns Error 410
 
**Expected behavior**
Bot just plays the song like normal.

**Environment (add if possible)**
* Node.js version: 14.17.6

**Additional information & screenshots**

![image](https://user-images.githubusercontent.com/18380794/134737207-3022d4a2-1ba2-4585-a35f-cb9c1984fc8b.png)
![image](https://user-images.githubusercontent.com/18380794/134737244-14717fd5-2d39-4777-9116-cb78cf9e8cc0.png)

Don't mind the double ping by the bot. I had multiple instances going during that test. Still occurs with just one instance.

**Comment by eritislami** [comment] 2021-09-24 23:29
Duplicate of #934

**Closed by eritislami** 2021-09-24 23:29 UTC
Labels: bug: unconfirmed
