### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Blizzard2875** [eritislami/evobot#482] opened 2020-12-10 19:27 UTC
Error: Error parsing info: Unable to retrieve video metadata
![image](https://user-images.githubusercontent.com/69636466/101819879-ba435f80-3b1d-11eb-85e2-ab0e1b7ec169.png)

**Comment by eritislami** [comment] 2020-12-10 19:52
If you haven't run a git pull in the last week you can try these steps, if not theres nothing to do about it.

- delete node_modules folder
- git pull, to get latest changes
- npm install
- try again

In the end there is no guarantee that it will be fixed, sometimes ytdl can't get the video info, it's not a bug.

**Closed by eritislami** 2020-12-10 19:52 UTC
Labels: bug: unconfirmed
