### ISSUE TITLE
Bug: Status Code 429 And Sending Too Much Command Respond

### ISSUE THREAD

**Issue by ZaNeksuto** [eritislami/evobot#608] opened 2021-01-28 01:20 UTC
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. make it less respond example : the help commands is sending 2 help message per command
2.
 
**Expected behavior**
A description of what you expected to happen.
only 1 message or respond per command
**Environment (add if possible)**
* Node.js version: 6.14.9

heres screenshot
https://media.discordapp.net/attachments/749266257886445596/804158193323343922/unknown.png?width=475&height=683
https://media.discordapp.net/attachments/749266257886445596/804158354225102898/unknown.png

**Comment by mozzi-berilinky** [comment] 2021-01-28 02:42
There is nothing wrong with the bot's code, and it seems that you used the bot's token twice.
The 429 error is caused by making too many requests to the server in a short period of time, and is not exactly an error.
Wait about 3 days and it will be resolved in the future.

**Comment by eritislami** [comment] 2021-01-28 04:15
You have started the same bot two times or using same token in different bots...

**Closed by eritislami** 2021-01-28 04:15 UTC
Labels: bug: unconfirmed

**Comment by wolf-yuan-6115** [comment] 2021-01-30 01:16
And please don't use Node js 6 anymore, use 12 instead
