### ISSUE TITLE
Bug: Error StatusCode:429 

### ISSUE THREAD

**Issue by Itz-MrJ** [eritislami/evobot#661] opened 2021-02-27 16:11 UTC
`MinigetError: Status code: 429
    at ClientRequest.<anonymous> (/home/runner/GracefulOilyIntroductory/node_modules/miniget/dist/index.js:204:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12) {
  statusCode: 429
}`

I'm getting this error in my console whenever I try to play a song. Can you please help me find a solution for this. The bot was working fine last night. But all of a sudden now, I have started getting this error now. Please help me.

**Comment by ndbiaw** [comment] 2021-02-28 11:14
Same here, just restart client

**Comment by Larkify** [comment] 2021-02-28 17:52
Duplicate of **[Issue #623](https://github.com/eritislami/evobot/issues/623)**

**Closed** 2021-03-04 05:58 UTC
Labels: bug: unconfirmed
