### ISSUE TITLE
Make the bot never leave the voice channel

### ISSUE THREAD

**Issue by Jordaar** [eritislami/evobot#154] opened 2020-08-14 11:58 UTC
I would love to see a feature in these bot that don't allow the bot to disconnect from the voice channel..

**Comment by KizutoChan** [comment] 2020-08-14 12:03
But if the bot doesn't automatically disconnect, it will cause problems

**Comment by Jordaar** [comment] 2020-08-14 12:18
There are many discord bot's that don't leave voice channel...take for example Groovy.....is there a possible way to do this?

**Comment by eritislami** [comment] 2020-08-15 12:59
Duplicate of #153

**Closed by eritislami** 2020-08-15 12:59 UTC
Labels: enhancement
