### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by ImPoppy03** [eritislami/evobot#82] opened 2020-06-17 19:25 UTC
TypeError: Cannot read property 'title' of undefined
    at Object.execute (C:\Users\Discord\Desktop\Alpha Music\commands\play.js:75:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Is the problem due to any module?

**Comment by ParasDeshpande** [comment] 2020-06-18 13:41
Yup this is a bug i guess, the same issue is happening with me when i try to play a playlist. I think there are some change in the module... @eritislami 
```
Error: resource youtube#playlistListResponse not found
    at D:\Other\Bot Coding\Bots\New folder\evobot\node_modules\simple-youtube-api\src\Request.js:35:68
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (D:\Other\Bot Coding\Bots\New folder\evobot\commands\playlist.js:53:20)
(node:2988) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of null
    at Object.execute (D:\Other\Bot Coding\Bots\New folder\evobot\commands\playlist.js:87:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by eritislami** [comment] 2020-06-18 14:59
> If the playlist is private, the error is not handled properly, this is the reason for this issue.

@ImPoppy03 you need to provide more details about your problem...

- Did you make changes to the code and now it's not working? if yes then download a clone of the repo and try again.
- If you didn't make changes and you are getting this error on the latest version of the bot, post the code from the file where you are getting the error

**Comment by ImPoppy03** [comment] 2020-06-18 15:43
I think this problem is caused by a missing module. Because this problem happened after VDS.

**Comment by ImPoppy03** [comment] 2020-06-18 15:44
error file is play.js our play.js files are same.

**Comment by ImPoppy03** [comment] 2020-06-18 16:30
Can you send your package.json file please ? @ParasDeshpande

**Comment by ImPoppy03** [comment] 2020-06-18 17:17
![2](https://user-images.githubusercontent.com/35898684/85051886-c10d9d00-b1a0-11ea-8779-5cd0c2ca17fb.png)
![1](https://user-images.githubusercontent.com/35898684/85051890-c23eca00-b1a0-11ea-91b1-9782bc6a1b12.png)

**Comment by RedzStar** [comment] 2020-06-19 20:31
I have the same issue. Hope there could be a solution soon!

**Comment by eritislami** [comment] 2020-06-19 20:48
> I think this problem is caused by a missing module.

Can't help you if you don't want to show your code, your error says property title is undefined on line 75, but on the latest code that error should have said line 78.
Are you really sure the code is the same?
https://github.com/eritislami/evobot/blob/f49327e4194416d0e5b028f32d6da3b8c4c9adb3/commands/play.js#L70-L90

**Comment by prgofficial69** [comment] 2020-06-21 14:22
Full code is here.. i tried hosting with Heroku and glitch. same error am getting. title is undefined.


const { play } = require("../include/play");
const { YOUTUBE_API_KEY } = require("../config.json");
const ytdl = require("ytdl-core");
const YouTubeAPI = require("simple-youtube-api");
const youtube = new YouTubeAPI(YOUTUBE_API_KEY);

module.exports = {
  name: "play",
  cooldown: 3,
  aliases: ["p"],
  description: "Plays audio from YouTube",
  async execute(message, args) {
    const { channel } = message.member.voice;

    const serverQueue = message.client.queue.get(message.guild.id);
    if (serverQueue && channel !== message.guild.me.voice.channel)
      return message.reply(`You must be in the same channel as ${message.client.user}`).catch(console.error);

    if (!args.length)
      return message
        .reply(`Usage: ${message.client.prefix}play <YouTube URL | Video Name>`)
        .catch(console.error);
    if (!channel) return message.reply("You need to join a voice channel first!").catch(console.error);

    const permissions = channel.permissionsFor(message.client.user);
    if (!permissions.has("CONNECT"))
      return message.reply("Cannot connect to voice channel, missing permissions");
    if (!permissions.has("SPEAK"))
      return message.reply("I cannot speak in this voice channel, make sure I have the proper permissions!");

    const search = args.join(" ");
    const videoPattern = /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+$/gi;
    const playlistPattern = /^.*(list=)([^#\&\?]*).*/gi;
    const url = args[0];
    const urlValid = videoPattern.test(args[0]);

    // Start the playlist if playlist url was provided
    if (!videoPattern.test(args[0]) && playlistPattern.test(args[0])) {
      return message.client.commands.get("playlist").execute(message, args);
    }

    const queueConstruct = {
      textChannel: message.channel,
      channel,
      connection: null,
      songs: [],
      loop: false,
      volume: 100,
      playing: true
    };

    let songInfo = null;
    let song = null;

    if (urlValid) {
      try {
        songInfo = await ytdl.getInfo(url);
        song = {
          title: songInfo.videoDetails.title,
          url: songInfo.videoDetails.video_url,
          duration: songInfo.videoDetails.lengthSeconds
        };
      } catch (error) {
        if (error.message.includes("copyright")) {
          return message
            .reply("⛔ The video could not be played due to copyright protection ⛔")
            .catch(console.error);
        } else {
          console.error(error);
          return message.reply(error.message).catch(console.error);
        }
      }
    } else {
      try {
        const results = await youtube.searchVideos(search, 1);
        songInfo = await ytdl.getInfo(results[0].url);
        song = {
          title: songInfo.videoDetails.title,
          url: songInfo.videoDetails.video_url,
          duration: songInfo.videoDetails.lengthSeconds
        };
      } catch (error) {
        console.error(error);
        return message.reply("No video was found with a matching title").catch(console.error);
      }
    }

    if (serverQueue) {
      serverQueue.songs.push(song);
      return serverQueue.textChannel
        .send(`✅ **${song.title}** has been added to the queue by ${message.author}`)
        .catch(console.error);
    }

    queueConstruct.songs.push(song);
    message.client.queue.set(message.guild.id, queueConstruct);

    try {
      queueConstruct.connection = await channel.join();
      play(queueConstruct.songs[0], message);
    } catch (error) {
      console.error(`Could not join voice channel: ${error}`);
      message.client.queue.delete(message.guild.id);
      await channel.leave();
      return message.channel.send(`Could not join the channel: ${error}`).catch(console.error);
    }
  }
};

**Comment by eritislami** [comment] 2020-06-21 15:35
@prgofficial69 can you please upload your package.json & package-lock.json to https://gist.github.com/ and link it here ? Im pretty sure your ytdl-core is outdated

**Comment by ImPoppy03** [comment] 2020-06-23 15:09
I fixed the problem. @eritislami
![2DARJgK2](https://user-images.githubusercontent.com/35898684/85421059-a8283180-b57c-11ea-8372-0bcfe9bd3b29.png)
Change this lines guys.

**Comment by ImPoppy03** [comment] 2020-06-23 15:20
I fixed the problem. @eritislami
Change this lines in play.js guys.
`song = {
title: songInfo.title,
url: songInfo.video_url,
duration: songInfo.lengthSeconds`

**Comment by eritislami** [comment] 2020-06-23 15:37
The problem is that you are using old version of [ytdl-core](https://www.npmjs.com/package/ytdl-core), but since you have fixed it your way i will close this

**Closed by eritislami** 2020-06-23 15:37 UTC
Labels: help

**Comment by impoppybutgithub** [comment] 2020-10-30 14:02
Can you delete all of my issues on evobot repository please ?
