### ISSUE TITLE
🐛 Bot stops playing music after about minute

### ISSUE THREAD

**Issue by robisxx** [eritislami/evobot#1365] opened 2023-02-28 21:03 UTC
**Describe the bug**
Bot just stops playing music after some time

**How To Reproduce**
1. used command to play music
2. playing music for some time (about one minute) and just stops with no error
 
**Expected behavior**

**Environment (add if possible)**
using evobot 2.5.2 on Ubuntu on Oracle free tier VPS.

**Comment by eritislami** [comment] 2023-02-28 21:24
Duplicate of #1242

**Closed by eritislami** 2023-02-28 21:24 UTC
