### ISSUE TITLE
Skip Voting

### ISSUE THREAD

**Issue by AmadeusWolf** [eritislami/evobot#142] opened 2020-07-30 18:07 UTC
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]
The feature is related to the skip command
**Describe the solution you'd like**
A description of what you want to happen.
it would be nice to see the skip command use votes if there are multiple people in the channel. e.g
1 member in VC: "skip" "Song skipped!"
2 members in VC: "skip" "Skip votes: 1/2"
**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Like with rythm where it requires the users to vote to skip a song

**Comment by eritislami** [comment] 2020-07-30 18:26
Thanks for the suggestion, this was requested before in another issue, if you have anything more to add you can discuss there to keep things tidy
Duplicate of #114

**Closed** 2020-07-30 18:28 UTC
Labels: enhancement
