### ISSUE TITLE
(node:2800) Api Error

### ISSUE THREAD

**Issue by XGDegi** [eritislami/evobot#1319] opened 2022-11-15 17:31 UTC
I have been trying to use the bot on my old laptop (win 10) and i just got an api error but that doesn't seem to be the issue cause the bot still put songs the issues start when the bot ends the song or you stop the song , the bot just stops and closes the command prompt  i tried restarting my laptop and also did some windows updates but it didn't fix anything. this is the error that pops up

(node:2800) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use node --trace-warnings ... to show where the warning was created)
C:\Users\op\Desktop\evobot-master\evobot-master\node_modules@discordjs\voice\src\VoiceConnection.ts:549
                        throw new Error('Cannot destroy VoiceConnection - it has already been destroyed');
         ^
Error: Cannot destroy VoiceConnection - it has already been destroyed
    at VoiceConnection2.destroy (C:\Users\op\Desktop\evobot-master\evobot-master\node_modules@discordjs\voice\src\VoiceConnection.ts:549:10)
    at Timeout._onTimeout (C:\Users\op\Desktop\evobot-master\evobot-master\structs\MusicQueue.ts:121:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

**Comment by eritislami** [comment] 2022-11-15 20:38
That's just a warning, the real issue is the connection error, and we already have open issues for those

Duplicate of #1279

**Closed by eritislami** 2022-11-15 20:38 UTC
