### ISSUE TITLE
Bug: Status code: 404

### ISSUE THREAD

**Issue by Marshxan** [eritislami/evobot#776] opened 2021-06-23 15:44 UTC
It Gives me Status code: 404 every time I want to play a song

I type +play then the song and it says <NAME>, Status code: 404 

and idk what that means will it be fixed as well

**Comment by wolf-yuan-6115** [comment] 2021-06-24 06:12
Dupe of: https://github.com/eritislami/evobot/issues/774

**Comment by D4rkk1** [comment] 2021-06-24 12:44
what exactly should i do to get it back up and running?

**Comment by sagnikoni** [comment] 2021-06-24 12:58
Same Problem.

**Comment by wolf-yuan-6115** [comment] 2021-06-24 17:36
> what exactly should i do to get it back up and running?

It's not ytdl-core down, ytdl-core didn't have backend server, it just a YouTube API crawler, there is some method to fix in previous issue https://github.com/eritislami/evobot/issues/774

**Comment by D4rkk1** [comment] 2021-06-25 20:50
when i execute playlist say playlist.usageReply, why?

**Comment by eritislami** [comment] 2021-06-26 14:52
4b4a2e84ff2b245c752631008f619d1232bb3f58

get newest commit & `npm install`

**Closed by eritislami** 2021-06-26 14:52 UTC
Labels: bug: unconfirmed
