### ISSUE TITLE
Can't Play Music? idk?

### ISSUE THREAD

**Issue by DEVBenSon** [eritislami/evobot#481] opened 2020-12-10 18:14 UTC
![image](https://user-images.githubusercontent.com/63822688/101812621-7fd4c500-3b13-11eb-8ef1-c4f75a66925c.png)

**Comment by AstethicDeath** [comment] 2020-12-10 18:30
i have ```
MinigetError: Status code: 429
    at ClientRequest.<anonymous> (/home/azuma/Bot/Criss/node_modules/miniget/dist/index.js:190:31)
```

**Comment by eritislami** [comment] 2020-12-10 19:50
You are using old packages, what you should try is:

- delete node_modules folder
- git pull, to get latest changes
- npm install
- try again

In the end there is no guarantee that it will be fixed, sometimes ytdl can't get the video info, it's not a bug.

**Closed by eritislami** 2020-12-10 19:50 UTC
Labels: bug: unconfirmed

**Comment by wolf-yuan-6115** [comment] 2020-12-16 09:52
Status 429 is `too many request` , try again later or reboot your bot if you are using Heroku
