### ISSUE TITLE
Bug: Error 403

### ISSUE THREAD

**Issue by Icelagy** [eritislami/evobot#302] opened 2020-11-02 21:26 UTC
I get this error when using "Play" command:

{
  code: 403,
  message: 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.',
  errors: [
    {
      message: 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.',
      domain: 'youtube.quota',
      reason: 'quotaExceeded'
    }
  ]
}

**Comment by L0SER8228** [comment] 2020-11-03 03:20
Change YouTube api key

**Comment by Icelagy** [comment] 2020-11-03 13:19
I already changed it, twice.

**Comment by wolf-yuan-6115** [comment] 2020-11-04 09:33
Try to reinstall module

**Comment by Icelagy** [comment] 2020-11-05 01:12
How do I reinstall modules.

**Comment by eritislami** [comment] 2020-11-06 00:17
Not a bug, moving to discussions

**Closed** 2020-11-06 00:18 UTC
Labels: bug: unconfirmed
